### ISSUE TITLE
Token Encryption Authentication

### ISSUE THREAD

**Issue by GoodBlokeAri** [l0c4lh057/AccountSwitcher#6]
The security feature whilst highly recommended can make the plugin tiresome to use especially if you're swapping accounts often. 

Could it be possible to enter the password to decrypt the tokens just once upon start up, or at least give the end-user options to select.

- Require password after (x) hours, or "Never"

Never obviously meaning, until next start-up. This way tokens can remain in their encrypted state but the end-user can switch accounts without having to enter the password every time.

**Comment by l0c4lh057** [comment]
good idea :)

this could be possible, but i would have to find a way to save the password in the plugin while not exposing it to the public. i think there is a way, but i will need to look it up.

the problem password is meant to encrypt the tokens, so nothing is able to read them, storing the password to decrypt them again would make the whole concept useless. but if i find a way i will add it. and if i find a way it does not matter if you need to type in the password again after some amount of time, because it is stored safely.

**Comment by l0c4lh057** [comment]
Ok, I just asked some other people to make sure the variable declaration is in fact out of scope from anything else, it is possible. I will then just make it save the token once you typed it in, until you restarted. I don't see the point in adding something that requires you to type it in again after some amount of time, if you don't want other people to switch accounts when you are not looking you should be responsible for that imo

**Comment by GoodBlokeAri** [comment]
fair enough, I just added that as to not lose sight of the initial protection and security the feature had. keeping it simple is probably the best as you mentioned. can't wait! :)

**Comment by GoodBlokeAri** [comment]
also: is it possible to maintain collapsed channels and categories? swapping accounts automatically expands all channels and categories and it can be disgruntling for servers with lots of channels 👍

**Comment by l0c4lh057** [comment]
it might be possible, but i rather not mess with discord's internal stuff. it just resets it whenever you login, there is no better way than saving it before switching and restoring it after you switched, i dont want to do that

**Comment by l0c4lh057** [comment]
added in ce652db
